name: Build llama.cpp binaries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Reponun içeriğini indir
      uses: actions/checkout@v3

    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: pip ve CMake yükle
      run: |
        python -m pip install --upgrade pip
        pip install cmake

    - name: Derleme işlemi başlasın
      run: |
        mkdir build
        cd build
        cmake .. -DLLAMA_BUILD_SERVER=ON
        cmake --build . --config Release

    - name: Derlenmiş dosyaları indirilebilir yap
      uses: actions/upload-artifact@v3
      with:
        name: llama_cpp_binaries
        path: build/Release/
